### ISSUE TITLE
Main bot spawn

### ISSUE THREAD

**Issue by PierrotMetille** [Compagnie-Hydromel/CompagnieHydromel#16]
Main bot spawn with baby shark music when the user cirth (fking me) are in a channel or start a live.

PLS fix this is a bit annoying.

**Comment by PierrotMetille** [comment]
George le barman more specifically

**Comment by PierrotMetille** [comment]
![MiddleFingerRonnieGIF](https://github.com/Compagnie-Hydromel/CompagnieHydromel/assets/79317647/ae6480ea-bd76-4b8a-9f31-562fb528a547)

**Comment by EthannSchneider** [comment]
Not an issue
