### ISSUE TITLE
Serveur adress in public description

### ISSUE THREAD

**Issue by PierrotMetille** [Compagnie-Hydromel/CompagnieHydromel#2]
The adress of the discord serveur "La compagnie de l'hydromel" is currenly in the public description of the repository. 

I dont think this is a good idea...

**Comment by PierrotMetille** [comment]
I duno if it's possible to put a link who ask serveur's owner permission before join, but put the link in public is to dangerous..

**Comment by EthannSchneider** [comment]
Will delete it but i was thinking someone that wanna help create the bot could join and test the bot on the server we can discuss later maybe
